### PR TITLE
Add description of the About API

### PR DESCRIPTION
**Pull request by j1m-ryan**
Describe the About API to the overview section

### CODE REVIEW

**Comment by lauralorenz** [comment]
Overall great addition, I'd love to make the image a little bit more precise and capture the difference between well-known properties and additional properties better. Maybe something like this?

About API description drawing


I shared the editable Google Drawing source for the above image to your email that was in your githuhb profile 👍

**Comment by j1m-ryan** [comment]
That's a much better image thanks!

**Comment by lauralorenz** [comment]
/lgtm
/approve

thanks!

**Pull request merged**
